# ==============================================================================
# TMUX CONFIGURATION
# ==============================================================================

# Source Keybindings & Theme Configuration
source-file ~/.config/tmux/keybindings.conf
source-file ~/.config/tmux/theme.conf

# General Settings
set -g mouse on
set -s escape-time 0
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# Load Plugins (via Nix profile stable paths)
run-shell ~/.nix-profile/share/tmux-plugins/sensible/sensible.tmux
run-shell ~/.nix-profile/share/tmux-plugins/vim-tmux-navigator/vim-tmux-navigator.tmux

set -g @resurrect-strategy-nvim 'session'
run-shell ~/.nix-profile/share/tmux-plugins/resurrect/resurrect.tmux

set -g @continuum-restore 'on'
set -g @continuum-save-interval '10'
run-shell ~/.nix-profile/share/tmux-plugins/continuum/continuum.tmux
